# Generated by Django 5.2.8 on 2025-11-22 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='имя', max_length=50)),
                ('last_name', models.CharField(db_column='фамилия', max_length=50)),
                ('birth_date', models.DateField(blank=True, db_column='дата_рождения', null=True)),
            ],
            options={
                'db_table': 'тренеры',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(db_column='id_матча', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='дата')),
                ('status', models.CharField(choices=[('запланирован', 'Запланирован'), ('идёт', 'Идёт'), ('завершён', 'Завершён')], db_column='статус', default='запланирован', max_length=20)),
            ],
            options={
                'db_table': 'матчи',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(db_column='id_игрока', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='имя', max_length=50)),
                ('last_name', models.CharField(db_column='фамилия', max_length=50)),
                ('birth_date', models.DateField(blank=True, db_column='дата_рождения', null=True)),
                ('position', models.CharField(choices=[('ВРТ', 'Вратарь'), ('ЗАЩ', 'Защитник'), ('ПЗ', 'Полузащитник'), ('НАП', 'Нападающий')], db_column='позиция', max_length=3)),
            ],
            options={
                'db_table': 'игроки',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(db_column='id_команды', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='название', max_length=100)),
                ('city', models.CharField(blank=True, db_column='город', max_length=50, null=True)),
                ('emblem', models.CharField(blank=True, db_column='эмблема', help_text='Путь к файлу эмблемы или URL', max_length=255, null=True)),
                ('coach', models.ForeignKey(blank=True, db_column='FK_id_тренера', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='football.coach')),
            ],
            options={
                'db_table': 'команды',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(db_column='id_события', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('гол', 'Гол'), ('ассист', 'Голевой пас'), ('автогол', 'Автогол'), ('пенальти_гол', 'Гол с пенальти'), ('желтая', 'Жёлтая карточка'), ('красная', 'Красная карточка'), ('замена', 'Замена')], db_column='тип', max_length=20)),
                ('minute', models.IntegerField(db_column='минута')),
                ('added_time', models.IntegerField(blank=True, db_column='добавленное_время', null=True)),
                ('match', models.ForeignKey(db_column='FK_id_матча', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='football.match')),
                ('player', models.ForeignKey(blank=True, db_column='FK_id_игрока', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='football.player')),
                ('team', models.ForeignKey(db_column='FK_id_команды', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='football.team')),
            ],
            options={
                'db_table': 'события_матча',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(db_column='FK_id_команды_гостей', on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='football.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(db_column='FK_id_команды_хозяев', on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='football.team'),
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.AutoField(db_column='id_записи', primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('ВРТ', 'Вратарь'), ('ЗАЩ', 'Защитник'), ('ПЗ', 'Полузащитник'), ('НАП', 'Нападающий')], db_column='позиция', default='ПЗ', max_length=3)),
                ('is_starting', models.BooleanField(db_column='в_старте', default=False)),
                ('match', models.ForeignKey(db_column='FK_id_матча', on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='football.match')),
                ('player', models.ForeignKey(db_column='FK_id_игрока', on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='football.player')),
                ('team', models.ForeignKey(db_column='FK_id_команды', on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='football.team')),
            ],
            options={
                'db_table': 'состав_на_матч',
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(db_column='id_состава', primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, db_column='номер', null=True)),
                ('player', models.ForeignKey(db_column='FK_id_игрока', on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='football.player')),
                ('team', models.ForeignKey(db_column='FK_id_команды', on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='football.team')),
            ],
            options={
                'db_table': 'игроки_команд',
                'unique_together': {('team', 'player')},
            },
        ),
    ]
